### ISSUE TITLE
Feature Request - Bungeecord&Velocity support

### ISSUE THREAD

**Issue by myavuzokumus** [AusTechDev/BetterReports#22]
Can you add support for BungeeCord and Velocity? Because i need using in my proxy server. At the same time, if I can see on which server it is reported in the report, I would greatly appreciate it.

And more things, whitelist servers.

**Comment by mnewt00** [comment]
Hey, thanks for creating an issue. We'll work towards getting BR on BungeeCord.

**Comment by myavuzokumus** [comment]
If you want tester, i can.

**Comment by mnewt00** [comment]
@Timmy109 any updates?

**Comment by myavuzokumus** [comment]
Also i need Velocity support.

**Comment by Timmy109** [comment]
It's in progress. I only just saw this now but I get working on it more.

**Comment by myavuzokumus** [comment]
> It's in progress. I only just saw this now but I get working on it more.

What is the latest status?
