### ISSUE TITLE
Feature Request - Text field for discord message

### ISSUE THREAD

**Issue by Firav** [AusTechDev/BetterReports#24]
Would there be a possibility to add a text field for the embed thats sent to the Discord? That way tags can be used to alert roles?

**Comment by Timmy109** [comment]
Hey, you can tag roles in discord using <@&ROLEID>

Replace ROLEID with the id of the role you want to tag and paste the whole thing into a field in the embed.

For example, <@&753093643044257895> will show up as @Owner in our Discord server

**Comment by Firav** [comment]
While it tags the roll in the embed, it doesnt actually ping the role for a notification.

**Comment by Timmy109** [comment]
> While it tags the roll in the embed, it doesnt actually ping the role for a notification.

Ah yep my bad I read it wrong. I'll work on something to address this.

**Comment by Timmy109** [comment]
This issue has been fixed in the latest version which can be downloaded here: https://www.spigotmc.org/resources/betterreports-discord-support.83689/

8879edfa4f89a40888ef2f26e4acd56798543843

**Comment by Firav** [comment]
Thank you!
